# two images drupal and posgress

services:
  webserver:
    image: drupal:9 # 
    ports:
      - '8080:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
  database:
    image: postgres:14  # this will use the latest apache v2
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes: